# Node.js
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'Mandeepsheoran.CypressFramework'
    customCommand: 'run scripts'
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: '$(System.DefaultWorkingDirectory)/_Mandeepsheoran.CypressFramework'
    customCommand: 'run scripts'
- task: NodeTool@0
  inputs:
    versionSpec: '16.17'
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
