version: "3"
services:
  # this container will run Cypress test using built-in Electron browser
  e2e-electron:
    image: "mandeep1989/cypressdemo:1.10"
    command: "electrontest-mocha"
    volumes:
      - ./cypress/videos:/cypress-docker/cypress/videos
      - ./cypress/reports:/cypress-docker/cypress/reports

  # this container will run Cypress test using Chrome browser
  e2e-chrome:
    image: "mandeep1989/cypressdemo:1.10"
    command: "chrometest-mocha"
    volumes:
      - ./cypress/videos:/cypress-docker/cypress/videos
      - ./cypress/reports:/cypress-docker/cypress/reports

  # this container will run Cypress test using Firefox browser
  # note that both Chrome and Firefox browsers were pre-installed in the Docker image
  e2e-firefox:
    image: "mandeep1989/cypressdemo:1.10"
    command: "firefoxtest-mocha"
    # if you want to debug FF run, pass DEBUG variable like
    environment:
      - DEBUG=cypress:server:browsers:firefox-util,cypress:server:util:process_profiler
    volumes:
      - ./cypress/videos:/cypress-docker/cypress/videos
      - ./cypress/reports:/cypress-docker/cypress/reports